import type { AppState } from "./types";

export const STATE_VERSION = 1;

const villa = "villa-wassenaar";
const penthouse = "penthouse-rotterdam";
const bistro = "bistro-noord";

export const seed: AppState = {
  version: STATE_VERSION,
  currentUserId: "janine",
  users: [
    { id: "janine", name: "Janine Slaats", role: "owner", email: "info@miminteriors.com", company: "mim | interiors", projectIds: [], twoFactor: true },
    { id: "sanne", name: "Sanne de Vries", role: "client", email: "sanne@voorbeeld.nl", projectIds: [villa], twoFactor: false },
    { id: "mark", name: "Mark Jansen", role: "client", email: "mark@voorbeeld.nl", projectIds: [penthouse], twoFactor: true },
    { id: "eva", name: "Eva Bakker", role: "client", email: "eva@bistronoord.nl", company: "Horeca Groep Noord", projectIds: [bistro], twoFactor: false },
    { id: "pieter", name: "Pieter van Dijk", role: "contractor", email: "planning@voorbeeld-vandijk.nl", company: "Bouwbedrijf Van Dijk", trade: "Aannemer", projectIds: [villa], accessUntil: "2027-03-28", twoFactor: true },
    { id: "anouk", name: "Anouk Smit", role: "contractor", email: "info@voorbeeld-dekwast.nl", company: "Schildersbedrijf De Kwast", trade: "Schilder & stucwerk", projectIds: [villa], accessUntil: "2027-03-28", twoFactor: false },
    { id: "daan", name: "Daan Bos", role: "contractor", email: "werk@voorbeeld-elektrobos.nl", company: "Elektro Bos", trade: "Elektricien", projectIds: [villa, penthouse], accessUntil: "2027-05-31", twoFactor: true },
    { id: "hout", name: "Ruben Hout", role: "contractor", email: "werkplaats@voorbeeld-houtenco.nl", company: "Meubelmakerij Hout & Co", trade: "Meubelmaker", projectIds: [villa], accessUntil: "2027-03-28", twoFactor: false },
    { id: "linteloo", name: "Mila Martens", role: "supplier", email: "dealer@voorbeeld-linteloo.nl", company: "Linteloo", projectIds: [], twoFactor: false },
  ],
  projects: [
    {
      id: villa,
      name: "Villa Wassenaar",
      clientId: "sanne",
      address: "Lange Kerkdam 12, Wassenaar",
      phase: "uitvoering",
      budget: 145000,
      showBudgetToClient: true,
      startDate: "2026-05-12",
      deliveryDate: "2027-02-26",
      rooms: ["Woonkamer", "Keuken", "Hal", "Badkamer", "Master bedroom"],
      coverColors: ["#d8cbb8", "#a48a6c", "#5f5a4e"],
      intake: {
        woningtype: "Vrijstaande villa, jaren dertig",
        ruimtes: ["Woonkamer", "Keuken", "Hal", "Badkamer", "Master bedroom"],
        stijl: ["Warm minimalisme", "Japandi"],
        budgetIndicatie: 145000,
        opleveringGewenst: "2027-03-01",
        focus: ["Woonkamer", "Keuken"],
        mustHaves: "Eettafel voor tien personen, veel opbergruimte in de hal",
        donts: "Hoogglans, chroom, koud wit licht",
        praktisch: "Vloerverwarming blijft, keuken blijft op dezelfde plek",
        huishouden: "Twee volwassenen, twee kinderen (8 en 11)",
        kinderen: true,
        huisdieren: true,
        thuiswerken: true,
        updatedAt: "2026-05-20T20:15:00",
      },
      internal: { hourlyRate: 95, hoursBudget: 240, hoursSpent: 196, bufferPct: 8 },
    },
    {
      id: penthouse,
      name: "Penthouse Kop van Zuid",
      clientId: "mark",
      address: "Wilhelminakade 88, Rotterdam",
      phase: "ontwerp",
      budget: 90000,
      showBudgetToClient: false,
      startDate: "2026-08-04",
      deliveryDate: "2027-04-30",
      rooms: ["Woonkamer", "Keuken", "Werkkamer", "Slaapkamer"],
      coverColors: ["#e6e1d8", "#8e9383", "#2f302c"],
      intake: {
        woningtype: "Penthouse, nieuwbouw 2019",
        ruimtes: ["Woonkamer", "Keuken", "Werkkamer", "Slaapkamer"],
        stijl: ["Modern", "Industrieel"],
        budgetIndicatie: 90000,
        opleveringGewenst: "2027-05-01",
        focus: ["Woonkamer", "Werkkamer"],
        mustHaves: "Akoestiek in de woonkamer, volwaardige werkplek",
        donts: "Veel kleur",
        praktisch: "Lift naar de woning is 2,10 m hoog",
        huishouden: "Eén volwassene, vaak gasten",
        kinderen: false,
        huisdieren: false,
        thuiswerken: true,
        updatedAt: "2026-08-10T09:00:00",
      },
      internal: { hourlyRate: 95, hoursBudget: 160, hoursSpent: 64, bufferPct: 10 },
    },
    {
      id: bistro,
      name: "Bistro Noord",
      clientId: "eva",
      address: "Noorderstraat 4, Amsterdam",
      phase: "intake",
      budget: 210000,
      showBudgetToClient: true,
      startDate: "2026-09-22",
      deliveryDate: "2027-06-15",
      rooms: ["Restaurant", "Bar", "Toiletten", "Terras"],
      coverColors: ["#c9a98a", "#7a4f36", "#2b2420"],
      intake: { ruimtes: ["Restaurant", "Bar", "Toiletten", "Terras"] },
      internal: { hourlyRate: 105, hoursBudget: 300, hoursSpent: 12, bufferPct: 12 },
    },
  ],
  mood: [
    { id: "m1", projectId: villa, room: "Woonkamer", title: "Warm kalkstuc", kind: "materiaal", colors: ["#e7dccb", "#d6c6ae", "#c4b097"], note: "Kalkverf met lichte wolkenstructuur op alle wanden." },
    { id: "m2", projectId: villa, room: "Woonkamer", title: "Kleurpalet", kind: "kleur", colors: ["#efe9df", "#cbbba3", "#8c7a63", "#4d463d"], note: "Zand, linnen en donker walnoot." },
    { id: "m3", projectId: villa, room: "Keuken", title: "Donker eiken en travertin", kind: "materiaal", colors: ["#3b3631", "#a39280", "#e6dccb"] },
    { id: "m4", projectId: villa, room: "Hal", title: "Ontvangst in brons", kind: "sfeer", colors: ["#d9cdb9", "#8a6a45", "#2f2a25"], note: "Warm, gedimd licht en een bronzen accent bij binnenkomst." },
    { id: "m5", projectId: penthouse, room: "Woonkamer", title: "Microcement en zwart staal", kind: "materiaal", colors: ["#cfcac1", "#9a968e", "#2c2c2a"] },
  ],
  choices: [
    {
      id: "c1",
      projectId: villa,
      room: "Woonkamer",
      question: "Welke vloer komt in woonkamer en keuken?",
      deadline: "2026-09-15",
      options: [
        { id: "a", label: "Brede plank eiken naturel", description: "Rustig en tijdloos, past binnen budget.", colors: ["#c9ad86", "#b39670"], priceDelta: 0 },
        { id: "b", label: "Visgraat eiken gerookt", description: "Warmer en klassieker, sluit aan op de jaren-dertig-details.", colors: ["#8c6a4c", "#6f523b"], priceDelta: 2400 },
        { id: "c", label: "Microcement", description: "Naadloos en strak, minder warm.", colors: ["#cfc8bd", "#b7afa3"], priceDelta: 1100 },
      ],
      chosenOptionId: "b",
      decidedAt: "2026-09-14T19:40:00",
    },
    {
      id: "c2",
      projectId: villa,
      room: "Hal",
      question: "Welke wandlamp komt in de hal?",
      deadline: "2026-10-03",
      options: [
        { id: "a", label: "Messing bol", description: "Warm, reflecteert het brons uit het moodboard.", colors: ["#b89a62", "#e8dcc2"], priceDelta: 0 },
        { id: "b", label: "Linnen kap, zwart frame", description: "Zachter licht, grafisch silhouet.", colors: ["#e9e3d9", "#2b2a28"], priceDelta: -180 },
        { id: "c", label: "Travertin schaal", description: "Sculpturaal, sluit aan op de badkamer.", colors: ["#d9cdb9", "#b8a68a"], priceDelta: 640 },
      ],
    },
    {
      id: "c3",
      projectId: villa,
      room: "Badkamer",
      question: "Welke kranen komen in de badkamer?",
      deadline: "2026-09-30",
      options: [
        { id: "a", label: "Geborsteld brons", description: "Warm, past bij travertin.", colors: ["#8a6a45"], priceDelta: 0 },
        { id: "b", label: "Mat zwart", description: "Grafisch contrast.", colors: ["#2b2a28"], priceDelta: -220 },
      ],
    },
    {
      id: "c4",
      projectId: penthouse,
      room: "Woonkamer",
      question: "Welke akoestische oplossing in de woonkamer?",
      deadline: "2026-10-09",
      options: [
        { id: "a", label: "Akoestisch stucwerk plafond", description: "Onzichtbaar, hoogste demping.", colors: ["#eeeae3"], priceDelta: 4800 },
        { id: "b", label: "Wandpanelen in wolvilt", description: "Zichtbaar materiaal, warmer.", colors: ["#9a968e", "#cfcac1"], priceDelta: 2900 },
      ],
    },
  ],
  products: [
    { id: "pr1", projectId: villa, room: "Keuken", name: "Eettafel eiken 280 cm", brand: "Hout & Co maatwerk", supplierName: "Meubelmakerij Hout & Co", sku: "HC-ET-280", price: 7800, purchasePrice: 6100, leadTimeWeeks: 10, status: "goedgekeurd", actionBy: "studio", color: "#a3825f", visibleToClient: true, visibleToContractor: true, supplierVisibleToClient: true },
    { id: "pr2", projectId: villa, room: "Woonkamer", name: "Bank Bolton 3,2 m, bouclé naturel", brand: "Linteloo", supplierName: "Linteloo", supplierUserId: "linteloo", sku: "LT-BOL-320-BN", price: 9850, purchasePrice: 7880, leadTimeWeeks: 12, expectedDelivery: "2026-11-20", status: "besteld", actionBy: "supplier", color: "#e4dccd", visibleToClient: true, visibleToContractor: false, supplierVisibleToClient: false, internalNote: "20% dealerkorting, levering via studio, 30% aanbetaald." },
    { id: "pr3", projectId: villa, room: "Hal", name: "Wandlamp messing", brand: "Studio Henk", supplierName: "Studio Henk", sku: "SH-WL-MS", price: 690, purchasePrice: 520, leadTimeWeeks: 6, status: "voorgesteld", actionBy: "client", color: "#b89a62", visibleToClient: true, visibleToContractor: false, supplierVisibleToClient: false },
    { id: "pr4", projectId: villa, room: "Keuken", name: "Inbouwspot dimbaar 2700K (12×)", brand: "Modular", supplierName: "Technische Unie", sku: "MOD-SMB-27", price: 1680, purchasePrice: 1150, leadTimeWeeks: 2, status: "geleverd", actionBy: "contractor", color: "#d9d4cc", visibleToClient: true, visibleToContractor: true, supplierVisibleToClient: false },
    { id: "pr5", projectId: villa, room: "Woonkamer", name: "Kalkverf Lime Paint, tint Dune (40 l)", brand: "Pure & Original", supplierName: "Pure & Original", sku: "PO-LP-DUNE", price: 1240, purchasePrice: 890, leadTimeWeeks: 1, status: "geleverd", actionBy: "contractor", color: "#d6c6ae", visibleToClient: true, visibleToContractor: true, supplierVisibleToClient: true },
    { id: "pr6", projectId: villa, room: "Woonkamer", name: "Visgraatvloer eiken gerookt (68 m²)", brand: "Bolefloor", supplierName: "Parketcentrale", sku: "BF-VG-GR-68", price: 11900, purchasePrice: 8900, leadTimeWeeks: 5, expectedDelivery: "2026-10-22", status: "besteld", actionBy: "supplier", color: "#8c6a4c", visibleToClient: true, visibleToContractor: true, supplierVisibleToClient: false, internalNote: "Levertijd strak op planning vloer leggen." },
    { id: "pr7", projectId: villa, room: "Master bedroom", name: "Bed Ashley met linnen hoofdbord", brand: "Linteloo", supplierName: "Linteloo", supplierUserId: "linteloo", sku: "LT-ASH-180", price: 6200, purchasePrice: 5080, leadTimeWeeks: 10, status: "voorgesteld", actionBy: "client", color: "#c9c2b2", visibleToClient: true, visibleToContractor: false, supplierVisibleToClient: false },
    { id: "pr8", projectId: penthouse, room: "Werkkamer", name: "Bureaulamp Panthella Mini", brand: "Louis Poulsen", supplierName: "Louis Poulsen", sku: "LP-PAN-MINI", price: 495, purchasePrice: 395, leadTimeWeeks: 3, status: "voorgesteld", actionBy: "client", color: "#ece8e1", visibleToClient: true, visibleToContractor: false, supplierVisibleToClient: false },
  ],
  tasks: [
    { id: "t1", projectId: villa, title: "Leidingwerk en elektra aanleggen", assigneeId: "daan", start: "2026-09-21", due: "2026-10-02", status: "bezig", dependsOn: [], location: "Begane grond", photos: ["elektra-keuken-1.jpg"] },
    { id: "t2", projectId: villa, title: "Wanden stucen woonkamer en hal", assigneeId: "anouk", start: "2026-10-05", due: "2026-10-16", status: "open", dependsOn: ["t1"], location: "Woonkamer, hal", photos: [] },
    { id: "t3", projectId: villa, title: "Kalkverf aanbrengen", assigneeId: "anouk", start: "2026-10-19", due: "2026-10-23", status: "open", dependsOn: ["t2"], location: "Woonkamer", photos: [] },
    { id: "t4", projectId: villa, title: "Visgraatvloer leggen", assigneeId: "pieter", start: "2026-10-26", due: "2026-11-06", status: "open", dependsOn: ["t2"], location: "Woonkamer, keuken", photos: [] },
    { id: "t5", projectId: villa, title: "Inmeten maatwerkkasten hal", assigneeId: "hout", start: "2026-11-09", due: "2026-11-10", status: "open", dependsOn: ["t4"], location: "Hal", photos: [] },
    { id: "t6", projectId: villa, title: "Spots en wandlampen monteren", assigneeId: "daan", start: "2026-10-26", due: "2026-10-28", status: "open", dependsOn: ["t3"], location: "Keuken, hal", photos: [] },
    { id: "t7", projectId: villa, title: "Sloop oude keuken", assigneeId: "pieter", start: "2026-09-14", due: "2026-09-18", status: "klaar", dependsOn: [], location: "Keuken", photos: ["sloop-keuken.jpg", "sloop-keuken-2.jpg"] },
    { id: "t8", projectId: penthouse, title: "Voorbereiding groepenkast", assigneeId: "daan", start: "2026-11-02", due: "2026-11-04", status: "open", dependsOn: [], location: "Meterkast", photos: [] },
  ],
  milestones: [
    { id: "ms1", projectId: villa, title: "Ontwerp klaar", date: "2026-07-03", kind: "ontwerp", forClient: true, forContractor: false, done: true },
    { id: "ms2", projectId: villa, title: "Bestelling bank en vloer geplaatst", date: "2026-09-16", kind: "bestelling", forClient: true, forContractor: false, done: true },
    { id: "ms3", projectId: villa, title: "Start uitvoering", date: "2026-09-14", kind: "uitvoering", forClient: true, forContractor: true, done: true },
    { id: "ms4", projectId: villa, title: "Keuze wandlamp hal", date: "2026-10-03", kind: "keuze", forClient: true, forContractor: false, done: false },
    { id: "ms5", projectId: villa, title: "Factuur termijn 3", date: "2026-10-15", kind: "facturatie", forClient: false, forContractor: false, done: false },
    { id: "ms6", projectId: villa, title: "Levering visgraatvloer op locatie", date: "2026-10-22", kind: "levering", forClient: false, forContractor: true, done: false },
    { id: "ms7", projectId: villa, title: "Levering meubels woonkamer", date: "2026-11-20", kind: "levering", forClient: true, forContractor: false, done: false },
    { id: "ms8", projectId: villa, title: "Oplevering en styling", date: "2027-02-26", kind: "oplevering", forClient: true, forContractor: true, done: false },
    { id: "ms9", projectId: penthouse, title: "Presentatie schetsontwerp", date: "2026-10-15", kind: "ontwerp", forClient: true, forContractor: false, done: false },
  ],
  files: [
    {
      id: "f1", projectId: villa, folder: "Plattegronden", title: "Plattegrond woonkamer",
      versions: [
        { version: 1, uploadedAt: "2026-06-20T10:00:00", status: "afgekeurd", decidedBy: "sanne", decidedAt: "2026-06-24T20:00:00", note: "Eettafel liever bij het raam." },
        { version: 2, uploadedAt: "2026-07-08T10:00:00", status: "afgekeurd", decidedBy: "sanne", decidedAt: "2026-07-10T21:00:00", note: "Kast in de nis graag dieper." },
        { version: 3, uploadedAt: "2026-09-08T09:00:00", status: "goedgekeurd", decidedBy: "sanne", decidedAt: "2026-09-12T19:30:00" },
      ],
      visibleToClient: true, visibleToContractor: true, allowDownload: true, watermark: true, releaseOnApproval: true,
    },
    {
      id: "f2", projectId: villa, folder: "Werktekeningen", title: "Werktekening keuken",
      versions: [
        { version: 1, uploadedAt: "2026-08-14T10:00:00", status: "afgekeurd", decidedBy: "sanne", decidedAt: "2026-08-16T10:00:00", note: "Vaatwasser links van de spoelbak." },
        { version: 2, uploadedAt: "2026-08-20T10:00:00", status: "goedgekeurd", decidedBy: "sanne", decidedAt: "2026-08-22T18:00:00" },
      ],
      visibleToClient: true, visibleToContractor: true, allowDownload: true, watermark: true, releaseOnApproval: true,
    },
    {
      id: "f3", projectId: villa, folder: "Werktekeningen", title: "Elektraschema begane grond",
      versions: [
        { version: 1, uploadedAt: "2026-08-28T10:00:00", status: "goedgekeurd", decidedBy: "sanne", decidedAt: "2026-08-30T12:00:00" },
        { version: 2, uploadedAt: "2026-09-29T16:00:00", status: "ter-akkoord", note: "Extra wandcontactdozen kookeiland." },
      ],
      visibleToClient: true, visibleToContractor: true, allowDownload: true, watermark: true, releaseOnApproval: true,
    },
    {
      id: "f4", projectId: villa, folder: "3D renders", title: "Impressies woonkamer en keuken",
      versions: [{ version: 2, uploadedAt: "2026-07-01T10:00:00", status: "goedgekeurd", decidedBy: "sanne", decidedAt: "2026-07-03T15:00:00" }],
      visibleToClient: true, visibleToContractor: false, allowDownload: true, watermark: false, releaseOnApproval: false,
    },
    {
      id: "f5", projectId: villa, folder: "Ontwerp", title: "Lichtplan hal",
      versions: [{ version: 1, uploadedAt: "2026-09-30T11:00:00", status: "ter-akkoord" }],
      visibleToClient: true, visibleToContractor: false, allowDownload: false, watermark: true, releaseOnApproval: true,
    },
    {
      id: "f6", projectId: villa, folder: "Offertes", title: "Offerte honorarium",
      versions: [{ version: 1, uploadedAt: "2026-05-01T10:00:00", status: "goedgekeurd", decidedBy: "sanne", decidedAt: "2026-05-03T10:00:00" }],
      visibleToClient: true, visibleToContractor: false, allowDownload: true, watermark: false, releaseOnApproval: false,
    },
    {
      id: "f7", projectId: villa, folder: "Intern", title: "Inkoopoverzicht en marges",
      versions: [{ version: 4, uploadedAt: "2026-09-28T17:00:00", status: "concept" }],
      visibleToClient: false, visibleToContractor: false, allowDownload: true, watermark: false, releaseOnApproval: false,
    },
    {
      id: "f8", projectId: villa, folder: "Foto's", title: "Voortgang sloop keuken",
      versions: [{ version: 1, uploadedAt: "2026-09-18T16:00:00", status: "goedgekeurd" }],
      visibleToClient: true, visibleToContractor: false, allowDownload: true, watermark: false, releaseOnApproval: false,
    },
    {
      id: "f9", projectId: penthouse, folder: "Plattegronden", title: "Schetsontwerp indeling",
      versions: [{ version: 1, uploadedAt: "2026-09-25T10:00:00", status: "concept" }],
      visibleToClient: true, visibleToContractor: false, allowDownload: false, watermark: true, releaseOnApproval: true,
    },
  ],
  comments: [
    { id: "k1", projectId: villa, targetType: "product", targetId: "pr3", channel: "klant", authorId: "sanne", text: "Mooi! Is er ook een versie die iets kleiner is?", at: "2026-09-29T20:10:00" },
    { id: "k2", projectId: villa, targetType: "product", targetId: "pr2", channel: "intern", authorId: "janine", text: "Linteloo bevestigt week 47. Aanbetaling is voldaan.", at: "2026-09-23T10:00:00" },
    { id: "k3", projectId: villa, targetType: "task", targetId: "t2", channel: "uitvoerder", authorId: "anouk", text: "Kan ik maandag starten, of is de elektra dan nog niet klaar?", at: "2026-10-01T07:45:00" },
    { id: "k4", projectId: villa, targetType: "file", targetId: "f1", channel: "klant", authorId: "janine", text: "Versie 3 heeft de eettafel bij het raam en de diepere nis. Laat je weten of dit zo goed is?", at: "2026-09-08T09:05:00" },
    { id: "k5", projectId: villa, targetType: "file", targetId: "f1", channel: "klant", authorId: "sanne", text: "Perfect zo, akkoord!", at: "2026-09-12T19:29:00" },
    { id: "k6", projectId: villa, targetType: "product", targetId: "pr2", channel: "leverancier", authorId: "linteloo", text: "Productie gestart, levering in week 47 bevestigd.", at: "2026-09-22T14:00:00" },
    { id: "k7", projectId: villa, targetType: "room", targetId: "Hal", channel: "klant", authorId: "sanne", text: "Kunnen we in de hal ook een plek voor de hondenmand maken?", at: "2026-09-30T21:00:00" },
  ],
  changeOrders: [
    { id: "co1", projectId: villa, reportedBy: "daan", title: "Extra wandcontactdozen kookeiland", description: "Vier extra dubbele wandcontactdozen in het kookeiland, inclusief aparte groep.", amount: 480, status: "voorgesteld", at: "2026-09-26T15:00:00" },
    { id: "co2", projectId: villa, reportedBy: "pieter", title: "Rotte balk onder vloer hal", description: "Bij het openleggen van de hal is een rotte draagbalk gevonden. Vervangen voordat de vloer gelegd wordt.", amount: 1250, status: "gemeld", at: "2026-10-01T11:30:00" },
  ],
  issues: [
    { id: "i1", projectId: villa, taskId: "t1", reportedBy: "daan", title: "Groepenkast vol: uitbreiding nodig voor inductie", status: "open", at: "2026-09-30T13:00:00" },
  ],
  agreements: [
    { projectId: villa, contractorId: "pieter", amount: 38500, scope: "Sloop, vloerconstructie, vloer leggen, timmerwerk" },
    { projectId: villa, contractorId: "anouk", amount: 9800, scope: "Stucwerk en kalkverf woonkamer en hal" },
    { projectId: villa, contractorId: "daan", amount: 7400, scope: "Elektra begane grond en verlichting" },
    { projectId: villa, contractorId: "hout", amount: 14200, scope: "Maatwerkkasten hal en eettafel" },
    { projectId: penthouse, contractorId: "daan", amount: 5200, scope: "Groepenkast en verlichting" },
  ],
  decisions: [
    { id: "d1", projectId: villa, at: "2026-05-03T10:00:00", byUserId: "sanne", subject: "Offerte honorarium", detail: "Akkoord op offerte honorarium versie 1." },
    { id: "d2", projectId: villa, at: "2026-08-22T18:00:00", byUserId: "sanne", subject: "Werktekening keuken", detail: "Akkoord op versie 2, vaatwasser links van de spoelbak." },
    { id: "d3", projectId: villa, at: "2026-08-30T12:00:00", byUserId: "sanne", subject: "Bank Bolton", detail: "Product goedgekeurd: bank Bolton 3,2 m, bouclé naturel.", consequence: "€ 9.850 uit budget inrichting" },
    { id: "d4", projectId: villa, at: "2026-09-12T19:30:00", byUserId: "sanne", subject: "Plattegrond woonkamer", detail: "Akkoord op versie 3." },
    { id: "d5", projectId: villa, at: "2026-09-14T19:40:00", byUserId: "sanne", subject: "Vloer woonkamer en keuken", detail: "Optie B gekozen: visgraat eiken gerookt.", consequence: "Meerprijs € 2.400" },
  ],
  audit: [
    { id: "a1", at: "2026-09-12T19:30:00", userId: "sanne", projectId: villa, action: "goedgekeurd", target: "Plattegrond woonkamer v3" },
    { id: "a2", at: "2026-09-29T16:00:00", userId: "janine", projectId: villa, action: "geüpload", target: "Elektraschema begane grond v2" },
    { id: "a3", at: "2026-09-30T08:12:00", userId: "daan", projectId: villa, action: "bekeken", target: "Elektraschema begane grond v1" },
    { id: "a4", at: "2026-09-30T11:00:00", userId: "janine", projectId: villa, action: "geüpload", target: "Lichtplan hal v1" },
    { id: "a5", at: "2026-10-01T11:30:00", userId: "pieter", projectId: villa, action: "gemeld", target: "Meerwerk: rotte balk onder vloer hal" },
  ],
};
