import type { AppState } from "./types";

export const STATE_VERSION = 4;

export const seed: AppState = {
  version: STATE_VERSION,
  role: "architect",
  contractorView: "van-dijk",
  projects: [
    {
      id: "villa-wassenaar",
      name: "Villa Wassenaar",
      clientName: "Sanne & Tom de Vries",
      clientEmail: "sanne@voorbeeld.nl",
      address: "Lange Kerkdam, Wassenaar",
      phase: "definitief",
      budget: 145000,
      startDate: "2026-05-12",
      deliveryDate: "2027-02-26",
      coverColors: ["#d8cbb8", "#a48a6c", "#5f5a4e"],
      rooms: ["Woonkamer", "Keuken", "Master bedroom", "Badkamer", "Entree"],
    },
    {
      id: "penthouse-rotterdam",
      name: "Penthouse Kop van Zuid",
      clientName: "Mark Jansen",
      clientEmail: "mark@voorbeeld.nl",
      address: "Wilhelminakade, Rotterdam",
      phase: "schetsontwerp",
      budget: 90000,
      startDate: "2026-08-04",
      deliveryDate: "2027-04-30",
      coverColors: ["#e6e1d8", "#8e9383", "#2f302c"],
      rooms: ["Woonkamer", "Keuken", "Werkkamer", "Slaapkamer"],
    },
    {
      id: "bistro-noord",
      name: "Bistro Noord",
      clientName: "Horeca Groep Noord",
      clientEmail: "info@bistronoord.nl",
      address: "Noorderstraat, Amsterdam",
      phase: "kennismaking",
      budget: 210000,
      startDate: "2026-09-22",
      deliveryDate: "2027-06-15",
      coverColors: ["#c9a98a", "#7a4f36", "#2b2420"],
      rooms: ["Restaurant", "Bar", "Toiletten", "Terras"],
    },
  ],
  mood: [
    {
      id: "m1",
      projectId: "villa-wassenaar",
      title: "Warm kalkstuc",
      room: "Woonkamer",
      kind: "materiaal",
      colors: ["#e7dccb", "#d6c6ae", "#c4b097"],
      note: "Kalkverf met lichte wolkenstructuur op alle wanden in de woonkamer.",
      addedBy: "architect",
      reaction: "love",
      comments: [
        { id: "c1", author: "client", text: "Prachtig! Kan dit ook in de hal?", at: "2026-09-14T10:12:00" },
        { id: "c2", author: "architect", text: "Zeker, ik neem het mee in de entree.", at: "2026-09-14T11:40:00" },
      ],
    },
    {
      id: "m2",
      projectId: "villa-wassenaar",
      title: "Gerookt eiken visgraat",
      room: "Woonkamer",
      kind: "materiaal",
      colors: ["#8c6a4c", "#6f523b", "#a3825f"],
      note: "Brede visgraat, geolied, doorlopend van woonkamer naar keuken.",
      addedBy: "architect",
      comments: [],
    },
    {
      id: "m3",
      projectId: "villa-wassenaar",
      title: "Travertin & brons",
      room: "Badkamer",
      kind: "materiaal",
      colors: ["#d9cdb9", "#b8a68a", "#7b5c3a"],
      note: "Gezoet travertin op vloer en wand, kranen in geborsteld brons.",
      addedBy: "architect",
      reaction: "maybe",
      comments: [
        { id: "c3", author: "client", text: "Mooi, maar is travertin niet kwetsbaar?", at: "2026-09-20T19:03:00" },
      ],
    },
    {
      id: "m4",
      projectId: "villa-wassenaar",
      title: "Kleurpalet slaapkamer",
      room: "Master bedroom",
      kind: "kleur",
      colors: ["#e9e3d9", "#b9b3a2", "#7e8270", "#4a4b42"],
      note: "Gedempt saliegroen met linnen en donker olijf als accent.",
      addedBy: "architect",
      comments: [],
    },
    {
      id: "m5",
      projectId: "villa-wassenaar",
      title: "Zoals bij onze vrienden in Gent",
      room: "Keuken",
      kind: "inspiratie",
      colors: ["#3b3631", "#a39280", "#efe8dd"],
      note: "Donker kookeiland met lichte werkbladen, open planken.",
      addedBy: "client",
      comments: [],
    },
    {
      id: "m6",
      projectId: "penthouse-rotterdam",
      title: "Microcement & zwart staal",
      room: "Woonkamer",
      kind: "materiaal",
      colors: ["#cfcac1", "#9a968e", "#2c2c2a"],
      addedBy: "architect",
      comments: [],
    },
  ],
  briefings: [
    {
      projectId: "villa-wassenaar",
      answers: {
        styles: ["Warm minimalisme", "Japandi"],
        materials: ["Natuursteen", "Hout", "Linnen"],
        avoid: "Hoogglans, veel chroom",
        household: "Twee volwassenen, twee kinderen (8 en 11), een hond",
        mustHaves: "Grote eettafel voor 10 personen, veel opbergruimte in de entree",
        priorities: ["Duurzaamheid", "Onderhoudsgemak"],
        budgetComfort: "Binnen het afgesproken budget, uitschieters in overleg",
      },
      updatedAt: "2026-06-02T20:15:00",
    },
  ],
  docs: [
    {
      id: "d1",
      projectId: "villa-wassenaar",
      title: "Plattegrond begane grond",
      category: "tekening",
      version: 3,
      fileName: "VW_plattegrond_BG_v3.pdf",
      sizeKb: 2410,
      uploadedAt: "2026-09-25T09:00:00",
      status: "ter-goedkeuring",
    },
    {
      id: "d2",
      projectId: "villa-wassenaar",
      title: "Impressies woonkamer en keuken",
      category: "3d",
      version: 2,
      fileName: "VW_renders_woonkeuken_v2.pdf",
      sizeKb: 18300,
      uploadedAt: "2026-09-18T14:30:00",
      status: "goedgekeurd",
    },
    {
      id: "d3",
      projectId: "villa-wassenaar",
      title: "Overeenkomst van opdracht",
      category: "contract",
      version: 1,
      fileName: "Overeenkomst_DeVries.pdf",
      sizeKb: 320,
      uploadedAt: "2026-05-12T10:00:00",
      status: "goedgekeurd",
    },
    {
      id: "d4",
      projectId: "villa-wassenaar",
      title: "Verlichtingsplan",
      category: "tekening",
      version: 1,
      fileName: "VW_verlichtingsplan_v1.pdf",
      sizeKb: 1650,
      uploadedAt: "2026-09-28T16:00:00",
      status: "wijziging-gevraagd",
      feedback: "Graag dimbare spots boven het kookeiland.",
    },
    {
      id: "d5",
      projectId: "penthouse-rotterdam",
      title: "Lichtplan werkkamer",
      category: "tekening",
      version: 2,
      fileName: "PR_lichtplan_werkkamer_v2.pdf",
      sizeKb: 980,
      uploadedAt: "2026-09-26T15:20:00",
      status: "goedgekeurd",
    },
  ],
  products: [
    {
      id: "p1",
      projectId: "villa-wassenaar",
      room: "Woonkamer",
      name: "Bank Bolton, 3,2 m, bouclé naturel",
      supplierId: "linteloo",
      purchasePrice: 7880,
      price: 9850,
      qty: 1,
      leadTimeWeeks: 12,
      status: "goedgekeurd",
      color: "#e4dccd",
    },
    {
      id: "p2",
      projectId: "villa-wassenaar",
      room: "Woonkamer",
      name: "Salontafel travertin rond 110",
      supplierId: "studio-henk",
      purchasePrice: 1910,
      price: 2390,
      qty: 1,
      leadTimeWeeks: 8,
      status: "voorstel",
      color: "#d4c5ab",
    },
    {
      id: "p3",
      projectId: "villa-wassenaar",
      room: "Keuken",
      name: "Hanglamp PH5, messing",
      supplierId: "louis-poulsen",
      purchasePrice: 955,
      price: 1195,
      qty: 2,
      leadTimeWeeks: 4,
      status: "besteld",
      color: "#b89a62",
    },
    {
      id: "p4",
      projectId: "villa-wassenaar",
      room: "Master bedroom",
      name: "Bed Ashley met linnen hoofdbord",
      supplierId: "piet-boon",
      purchasePrice: 5080,
      price: 6200,
      qty: 1,
      leadTimeWeeks: 10,
      status: "voorstel",
      color: "#c9c2b2",
    },
    {
      id: "p6",
      projectId: "penthouse-rotterdam",
      room: "Werkkamer",
      name: "Bureaulamp Panthella Mini, opaal",
      supplierId: "louis-poulsen",
      purchasePrice: 395,
      price: 495,
      qty: 2,
      leadTimeWeeks: 3,
      status: "besteld",
      color: "#ece8e1",
    },
    {
      id: "p5",
      projectId: "villa-wassenaar",
      room: "Badkamer",
      name: "Kraanset geborsteld brons",
      supplierId: "vola",
      purchasePrice: 1470,
      price: 1840,
      qty: 2,
      leadTimeWeeks: 6,
      status: "geleverd",
      color: "#8a6a45",
    },
  ],
  milestones: [
    { id: "t1", projectId: "villa-wassenaar", title: "Kennismaking op locatie", date: "2026-05-12", type: "afspraak", location: "Wassenaar", done: true },
    { id: "t2", projectId: "villa-wassenaar", title: "Presentatie schetsontwerp", date: "2026-07-03", type: "mijlpaal", done: true },
    { id: "t3", projectId: "villa-wassenaar", title: "Materialen kiezen in de studio", date: "2026-10-08", type: "afspraak", location: "Studio mim", done: false },
    { id: "t4", projectId: "villa-wassenaar", title: "Definitief ontwerp gereed", date: "2026-10-30", type: "mijlpaal", done: false },
    { id: "t5", projectId: "villa-wassenaar", title: "Start uitvoering aannemer", date: "2026-11-23", type: "mijlpaal", done: false },
    { id: "t6", projectId: "villa-wassenaar", title: "Levering meubels woonkamer", date: "2027-02-10", type: "levering", done: false },
    { id: "t7", projectId: "villa-wassenaar", title: "Oplevering en styling", date: "2027-02-26", type: "mijlpaal", done: false },
    { id: "t8", projectId: "penthouse-rotterdam", title: "Presentatie schetsontwerp", date: "2026-10-15", type: "afspraak", location: "Op locatie", done: false },
  ],
  messages: [
    { id: "x1", projectId: "villa-wassenaar", author: "architect", text: "Goedemorgen Sanne en Tom! De nieuwe plattegrond (v3) staat klaar. Willen jullie die bekijken?", at: "2026-09-25T09:05:00" },
    { id: "x2", projectId: "villa-wassenaar", author: "client", text: "Dank je! We kijken er vanavond samen naar.", at: "2026-09-25T12:31:00" },
    { id: "x3", projectId: "villa-wassenaar", author: "client", text: "Kunnen we de materiaalafspraak op 8 oktober om 14:00 doen?", at: "2026-09-29T08:47:00" },
  ],
  invoices: [
    {
      id: "i1",
      projectId: "villa-wassenaar",
      kind: "offerte",
      number: "OF-2026-014",
      date: "2026-05-01",
      dueDate: "2026-05-31",
      status: "geaccepteerd",
      vatRate: 21,
      lines: [
        { description: "Ontwerpfase: schetsontwerp en definitief ontwerp", qty: 1, unitPrice: 14500 },
        { description: "Begeleiding uitvoering (uren)", qty: 80, unitPrice: 95 },
      ],
    },
    {
      id: "i2",
      projectId: "villa-wassenaar",
      kind: "factuur",
      number: "2026-031",
      date: "2026-07-03",
      dueDate: "2026-07-17",
      status: "betaald",
      vatRate: 21,
      lines: [{ description: "Termijn 1: schetsontwerp (40%)", qty: 1, unitPrice: 5800 }],
    },
    {
      id: "i3",
      projectId: "villa-wassenaar",
      kind: "factuur",
      number: "2026-044",
      date: "2026-09-26",
      dueDate: "2026-10-10",
      status: "verzonden",
      vatRate: 21,
      lines: [{ description: "Termijn 2: definitief ontwerp (40%)", qty: 1, unitPrice: 5800 }],
    },
  ],
  suppliers: [
    {
      id: "linteloo",
      name: "Linteloo",
      category: "Meubels",
      contactName: "Eva Martens",
      email: "dealer@voorbeeld-linteloo.nl",
      phone: "+31 20 000 00 01",
      website: "linteloo.com",
      accountNumber: "DL-4471",
      discountPct: 20,
      terms: "Levertijd 10 tot 14 weken, aanbetaling 30% bij order",
    },
    {
      id: "studio-henk",
      name: "Studio Henk",
      category: "Meubels",
      contactName: "Ruben de Boer",
      email: "trade@voorbeeld-studiohenk.nl",
      phone: "+31 20 000 00 02",
      website: "studiohenk.com",
      discountPct: 20,
      terms: "Franco levering vanaf € 2.500",
    },
    {
      id: "louis-poulsen",
      name: "Louis Poulsen",
      category: "Verlichting",
      contactName: "Mila Jansen",
      email: "projects@voorbeeld-louispoulsen.nl",
      phone: "+31 20 000 00 03",
      website: "louispoulsen.com",
      accountNumber: "NL-88213",
      discountPct: 20,
    },
    {
      id: "piet-boon",
      name: "Piet Boon Collection",
      category: "Meubels",
      contactName: "Sophie Visser",
      email: "dealers@voorbeeld-pietboon.nl",
      phone: "+31 20 000 00 04",
      website: "pietboon.com",
      discountPct: 18,
    },
    {
      id: "vola",
      name: "Vola",
      category: "Sanitair",
      contactName: "Jens Holm",
      email: "orders@voorbeeld-vola.nl",
      phone: "+31 20 000 00 05",
      website: "vola.com",
      discountPct: 20,
      terms: "Levering via groothandel, levertijd 4 tot 6 weken",
    },
  ],
  orders: [
    {
      id: "o1",
      number: "IO-2026-007",
      supplierId: "vola",
      projectId: "villa-wassenaar",
      productIds: ["p5"],
      date: "2026-08-12",
      expectedDelivery: "2026-09-20",
      deliverTo: "studio",
      status: "geleverd",
    },
    {
      id: "o2",
      number: "IO-2026-009",
      supplierId: "louis-poulsen",
      projectId: "villa-wassenaar",
      productIds: ["p3"],
      date: "2026-09-22",
      expectedDelivery: "2026-10-21",
      deliverTo: "project",
      status: "bevestigd",
    },
    {
      id: "o3",
      number: "IO-2026-010",
      supplierId: "louis-poulsen",
      projectId: "penthouse-rotterdam",
      productIds: ["p6"],
      date: "2026-09-30",
      deliverTo: "studio",
      status: "verstuurd",
    },
  ],
  contractors: [
    {
      id: "van-dijk",
      name: "Bouwbedrijf Van Dijk",
      trade: "Aannemer",
      contactName: "Pieter van Dijk",
      email: "planning@voorbeeld-vandijk.nl",
      phone: "+31 70 000 00 11",
      projectIds: ["villa-wassenaar"],
    },
    {
      id: "de-kwast",
      name: "Schildersbedrijf De Kwast",
      trade: "Schilder & stucwerk",
      contactName: "Anouk Smit",
      email: "info@voorbeeld-dekwast.nl",
      phone: "+31 70 000 00 12",
      projectIds: ["villa-wassenaar", "penthouse-rotterdam"],
    },
    {
      id: "elektro-bos",
      name: "Elektro Bos",
      trade: "Elektricien",
      contactName: "Daan Bos",
      email: "werk@voorbeeld-elektrobos.nl",
      phone: "+31 10 000 00 13",
      projectIds: ["penthouse-rotterdam"],
    },
  ],
  lastRead: {
    "villa-wassenaar": { architect: "2026-09-25T09:05:00", client: "2026-09-25T09:05:00" },
  },
};
